### create users include profiles
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name": "asto1",
    "email": "asto1@gmail.com",
    "password": "123456",
    "identity_type": "KTP",
    "identity_number": "1385658495212223",
    "address": "Jl. Fly"

}

### get all users
GET http://localhost:3000/api/v1/users

### get users by id
GET http://localhost:3000/api/v1/users/84

### update users includ profiles by id
PUT http://localhost:3000/api/v1/users/11
Content-Type: application/json

{
    "name": "pOke777",
    "email": "poke777@gmail.com",
    "password": "poke2",
    "identity_type": "KTP",
    "identity_number": "3578012412020127",
    "address": "Jl. Babatan No 3"

}

### delete users by id
DELETE http://localhost:3000/api/v1/users/

### create bank_accounts
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
    "bank_name": "Mandiri",
    "bank_account_number": "143947632227195",
    "balance": 750000,
    "user_id": 86
}

### get all accounts
GET http://localhost:3000/api/v1/accounts

### get account by id
GET http://localhost:3000/api/v1/accounts/24

### update accounts by id
PUT http://localhost:3000/api/v1/accounts/111
Content-Type: application/json

{
    "bank_name": "BCA Syariah",
    "bank_account_number": "2347651839587558",
    "balance": 200001
}

### delete accounts by id
DELETE http://localhost:3000/api/v1/accounts/86

### create transactions
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
    "amount": 100000,
    "sourceAccount": 7,
    "destinationAccount": 6
}

### get all transactions
GET http://localhost:3000/api/v1/transactions

### get transactions by id
GET http://localhost:3000/api/v1/transactions/23

### delete transactions by id
DELETE http://localhost:3000/api/v1/transactions/22

### register
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "name": "poke",
    "email": "poke@gmail.com",
    "password": "123456"
}

### login
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email": "poke@gmail.com",
    "password": "123456"
}

### login verified
GET http://localhost:3000/api/v1/authenticated
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsIm5hbWUiOiJwb2tlIiwiZW1haWwiOiJwb2tlQGdtYWlsLmNvbSIsImlhdCI6MTcxMzU0NzUzMn0.H91EIveo3NkiLS7lv3B_7YmavOZ_XEI59Os2RZ1POok